// Operadores de comparaçāo

/* 
  igual  (==)
  maior que (>)
  maior ou igual que  (>=)
  menor que  (<)
  menor ou igual que  (<=)
  diferente de (!=)
  equivalente (===)
  nao equivalente (!==)
*/

// console.log('comparacoes entre 5 e 10')
// console.log(5 == 10)
// console.log(5 > 10)
// console.log(5 >= 10)
// console.log(5 < 10)
// console.log(5 <= 10)
// console.log(5 != 10)
// console.log(5 === 10)
// console.log(5 !== 10)

// console.log('comparacoes entre 5 e 5')
// console.log(5 == 5)
// console.log(5 > 5)
// console.log(5 >= 5)
// console.log(5 < 5)
// console.log(5 <= 5)
// console.log(5 != 5)
// console.log(5 === 5)
// console.log(5 !== 5)

console.log("comparacoes entre 5 e '3'")
console.log(5 == '3')
console.log(5 > '3')
console.log(5 >= '3')
console.log(5 < '3')
console.log(5 <= '3')
console.log(5 != '3')
console.log(5 === '3')
console.log(5 !== '3')

console.log("comparacoes entre 5 e '5'")
console.log(5 == '5')
console.log(5 > '5')
console.log(5 >= '5')
console.log(5 < '5')
console.log(5 <= '5')
console.log(5 != '5')
console.log(5 === '5')
console.log(5 !== '5')

